# Generated by Django 4.0 on 2022-02-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='entry_date',
            field=models.DateTimeField(max_length=40),
        ),
    ]
