# Generated by Django 4.0 on 2022-05-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0003_alter_hr_form_interviewed_alter_hr_form_medicalval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hogar_employee',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='person_name1',
            field=models.CharField(default='Brandon', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='person_name2',
            field=models.CharField(default='Brandon', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='person_phone1',
            field=models.CharField(default='84948969', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='person_phone2',
            field=models.CharField(default='84948969', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='profesional_code',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='vehicle_description',
            field=models.CharField(default='Moto', max_length=40),
            preserve_default=False,
        ),
    ]
