# Generated by Django 4.0 on 2022-05-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0005_hr_form_interview_date_hr_form_interviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_form',
            name='test_file',
            field=models.FileField(default='test.txt', upload_to=''),
            preserve_default=False,
        ),
    ]
