# Generated by Django 4.0 on 2022-05-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0006_hr_form_test_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_form',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
